# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    pretix.url: '%env(string:PRETIX_URL)%'
    pretix.api_key: '%env(string:PRETIX_API_KEY)%'
    pretix.organiser: '%env(string:PRETIX_ORGANISER)%'
    pretix.event: '%env(string:PRETIX_EVENT)%'
    eboekhouden.api_token: '%env(string:E_BOEK_HOUDEN_API_TOKEN)%'
    eboekhouden.stripe_ledger: '%env(string:E_BOEK_HOUDEN_STRIPE_LEDGER)%'
    eboekhouden.paypal_ledger: '%env(string:E_BOEK_HOUDEN_PAYPAL_LEDGER)%'
    eboekhouden.stripe_costs_ledger: '%env(string:E_BOEK_HOUDEN_STRIPE_COSTS_LEDGER)%'
    eboekhouden.paypal_costs_ledger: '%env(string:E_BOEK_HOUDEN_PAYPAL_COSTS_LEDGER)%'
    eboekhouden.debtors_ledger: '%env(string:E_BOEK_HOUDEN_DEBTORS_LEDGER)%'
    eboekhouden.default_ledger: '%env(string:E_BOEK_HOUDEN_DEFAULT_LEDGER)%'
    stripe.secret_key: '%env(string:STIPE_SECRET_KEY)%'
    paypal.client_id: '%env(string:PAYPAL_CLIENT_ID)%'
    paypal.secret: '%env(string:PAYPAL_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\DataAccessLayer\Pretix\PretixApiClient:
        arguments:
            $client: '@http_client'
            $baseUrl: '%pretix.url%'
            $apiKey: '%pretix.api_key%'
            $event: '%pretix.event%'
            $organiser: '%pretix.organiser%'

    App\DataAccessLayer\EBoekHouden\EBoekHoudenApi:
        arguments:
            $serializer: '@serializer'
            $httpClient: '@http_client'
            $apiToken: '%eboekhouden.api_token%'

    App\DataAccessLayer\EBoekHouden\Repository\LedgerRepository:
        arguments:
            $serializer: '@serializer'
            $boekHoudenApi: '@App\DataAccessLayer\EBoekHouden\EBoekHoudenApi'
            $cache: '@cache.app'
            $stripeLedger: '%eboekhouden.stripe_ledger%'
            $paypalLedger: '%eboekhouden.paypal_ledger%'
            $stripeCostsLedger: '%eboekhouden.stripe_costs_ledger%'
            $paypalCostsLedger: '%eboekhouden.paypal_costs_ledger%'
            $debtorsLedger: '%eboekhouden.debtors_ledger%'
            $defaultLedger: '%eboekhouden.default_ledger%'

    App\DataAccessLayer\StripeWrapper:
        arguments:
            $stripeApiKey: '%stripe.secret_key%'

    App\DataAccessLayer\PayPal\PayPalApi:
        arguments:
            $httpClient: '@http_client'
            $serializer: '@serializer'
            $paypalClientId: '%paypal.client_id%'
            $paypalSecret: '%paypal.secret%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
